github.com:
    user: bugfrei
    oauth_token: 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
    git_protocol: https
    users:
        bugfrei:
            oauth_token: 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
